/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as PublicGalleryRouteImport } from './routes/_public/gallery'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ProtectedRequestsRouteImport } from './routes/_protected/requests'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCreateRequestRouteImport } from './routes/_protected/create-request'
import { Route as ProtectedChatRouteImport } from './routes/_protected/chat'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AdminGalleryRouteRouteImport } from './routes/admin/gallery/route'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery/index'
import { Route as ApiUploadthingSplatRouteImport } from './routes/api/uploadthing/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminGalleryCreateRouteImport } from './routes/admin/gallery/create'
import { Route as ProtectedRequestIdRouteImport } from './routes/_protected/request.$id'
import { Route as AdminGalleryIdEditRouteImport } from './routes/admin/gallery/$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedRequestsRoute = ProtectedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCreateRequestRoute = ProtectedCreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AdminGalleryRouteRoute = AdminGalleryRouteRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGalleryRouteRoute,
} as any)
const ApiUploadthingSplatRoute = ApiUploadthingSplatRouteImport.update({
  id: '/api/uploadthing/$',
  path: '/api/uploadthing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryCreateRoute = AdminGalleryCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminGalleryRouteRoute,
} as any)
const ProtectedRequestIdRoute = ProtectedRequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AdminGalleryIdEditRoute = AdminGalleryIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminGalleryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin/gallery': typeof AdminGalleryRouteRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/chat': typeof ProtectedChatRoute
  '/create-request': typeof ProtectedCreateRequestRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/requests': typeof ProtectedRequestsRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/request/$id': typeof ProtectedRequestIdRoute
  '/admin/gallery/create': typeof AdminGalleryCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/gallery/$id/edit': typeof AdminGalleryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/chat': typeof ProtectedChatRoute
  '/create-request': typeof ProtectedCreateRequestRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/requests': typeof ProtectedRequestsRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/request/$id': typeof ProtectedRequestIdRoute
  '/admin/gallery/create': typeof AdminGalleryCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/gallery/$id/edit': typeof AdminGalleryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRouteRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/chat': typeof ProtectedChatRoute
  '/_protected/create-request': typeof ProtectedCreateRequestRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/requests': typeof ProtectedRequestsRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/request/$id': typeof ProtectedRequestIdRoute
  '/admin/gallery/create': typeof AdminGalleryCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/gallery/$id/edit': typeof AdminGalleryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/admin/gallery'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/create-request'
    | '/dashboard'
    | '/requests'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/requests'
    | '/request/$id'
    | '/admin/gallery/create'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/admin/gallery/'
    | '/admin/gallery/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/$'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/create-request'
    | '/dashboard'
    | '/requests'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/requests'
    | '/request/$id'
    | '/admin/gallery/create'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/admin/gallery'
    | '/admin/gallery/$id/edit'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/admin'
    | '/$'
    | '/_auth'
    | '/admin/gallery'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_protected/chat'
    | '/_protected/create-request'
    | '/_protected/dashboard'
    | '/_protected/requests'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/gallery'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/requests'
    | '/_public/'
    | '/_protected/request/$id'
    | '/admin/gallery/create'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/admin/gallery/'
    | '/admin/gallery/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadthingSplatRoute: typeof ApiUploadthingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/requests': {
      id: '/_protected/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof ProtectedRequestsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/create-request': {
      id: '/_protected/create-request'
      path: '/create-request'
      fullPath: '/create-request'
      preLoaderRoute: typeof ProtectedCreateRequestRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof AdminGalleryRouteRoute
    }
    '/api/uploadthing/$': {
      id: '/api/uploadthing/$'
      path: '/api/uploadthing/$'
      fullPath: '/api/uploadthing/$'
      preLoaderRoute: typeof ApiUploadthingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery/create': {
      id: '/admin/gallery/create'
      path: '/create'
      fullPath: '/admin/gallery/create'
      preLoaderRoute: typeof AdminGalleryCreateRouteImport
      parentRoute: typeof AdminGalleryRouteRoute
    }
    '/_protected/request/$id': {
      id: '/_protected/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof ProtectedRequestIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/admin/gallery/$id/edit': {
      id: '/admin/gallery/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/gallery/$id/edit'
      preLoaderRoute: typeof AdminGalleryIdEditRouteImport
      parentRoute: typeof AdminGalleryRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedChatRoute: typeof ProtectedChatRoute
  ProtectedCreateRequestRoute: typeof ProtectedCreateRequestRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedRequestsRoute: typeof ProtectedRequestsRoute
  ProtectedRequestIdRoute: typeof ProtectedRequestIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedChatRoute: ProtectedChatRoute,
  ProtectedCreateRequestRoute: ProtectedCreateRequestRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedRequestsRoute: ProtectedRequestsRoute,
  ProtectedRequestIdRoute: ProtectedRequestIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminGalleryRouteRouteChildren {
  AdminGalleryCreateRoute: typeof AdminGalleryCreateRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
  AdminGalleryIdEditRoute: typeof AdminGalleryIdEditRoute
}

const AdminGalleryRouteRouteChildren: AdminGalleryRouteRouteChildren = {
  AdminGalleryCreateRoute: AdminGalleryCreateRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
  AdminGalleryIdEditRoute: AdminGalleryIdEditRoute,
}

const AdminGalleryRouteRouteWithChildren =
  AdminGalleryRouteRoute._addFileChildren(AdminGalleryRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminGalleryRouteRoute: typeof AdminGalleryRouteRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminGalleryRouteRoute: AdminGalleryRouteRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadthingSplatRoute: ApiUploadthingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
